// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:instant_grrocery_delivery/model/auth/response/auth_response.dart';
import 'package:instant_grrocery_delivery/model/cart/cart_item/cart_item.dart';
import 'package:instant_grrocery_delivery/model/coupon/coupon.dart';
import 'package:instant_grrocery_delivery/model/order/order.dart';
import 'package:instant_grrocery_delivery/model/order/order_item/order_item.dart';
import 'package:instant_grrocery_delivery/model/product/product.dart';
import 'package:instant_grrocery_delivery/model/user/user.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AuthResponseAdapter());
    registerAdapter(CartItemAdapter());
    registerAdapter(CouponAdapter());
    registerAdapter(OrderAdapter());
    registerAdapter(OrderItemAdapter());
    registerAdapter(ProductAdapter());
    registerAdapter(UserAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AuthResponseAdapter());
    registerAdapter(CartItemAdapter());
    registerAdapter(CouponAdapter());
    registerAdapter(OrderAdapter());
    registerAdapter(OrderItemAdapter());
    registerAdapter(ProductAdapter());
    registerAdapter(UserAdapter());
  }
}
