// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:instant_grrocery_delivery/features/auth/data/model/response/auth_response.dart';
import 'package:instant_grrocery_delivery/features/cart/data/model/cart_item/cart_item.dart';
import 'package:instant_grrocery_delivery/features/coupon/data/model/coupon.dart';
import 'package:instant_grrocery_delivery/features/order/data/model/order.dart';
import 'package:instant_grrocery_delivery/features/order/data/model/order_item/order_item.dart';
import 'package:instant_grrocery_delivery/features/product/data/model/product.dart';
import 'package:instant_grrocery_delivery/features/profile/data/model/user.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AuthResponseAdapter());
    registerAdapter(CartItemAdapter());
    registerAdapter(CouponAdapter());
    registerAdapter(OrderAdapter());
    registerAdapter(OrderItemAdapter());
    registerAdapter(ProductAdapter());
    registerAdapter(UserAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AuthResponseAdapter());
    registerAdapter(CartItemAdapter());
    registerAdapter(CouponAdapter());
    registerAdapter(OrderAdapter());
    registerAdapter(OrderItemAdapter());
    registerAdapter(ProductAdapter());
    registerAdapter(UserAdapter());
  }
}
