class Country {
  final String name;
  final String phoneCode;
  final String nameCode;
  final String flag;

  const Country(
    this.nameCode,
    this.phoneCode,
    this.name,
    this.flag,
  );

  static const Map<String, Country> countries = {
    "ad": Country("ad", "376", "Andorra", "🇦🇩"),
    "ae": Country("ae", "971", "United Arab Emirates (UAE)", "🇦🇪"),
    "af": Country("af", "93", "Afghanistan", "🇦🇫"),
    "ag": Country("ag", "1", "Antigua and Barbuda", "🇦🇬"),
    "ai": Country("ai", "1", "Anguilla", "🇦🇮"),
    "al": Country("al", "355", "Albania", "🇦🇱"),
    "am": Country("am", "374", "Armenia", "🇦🇲"),
    "ao": Country("ao", "244", "Angola", "🇦🇴"),
    "aq": Country("aq", "672", "Antarctica", "🇦🇶"),
    "ar": Country("ar", "54", "Argentina", "🇦🇷"),
    "as": Country("as", "1", "American Samoa", "🇦🇸"),
    "at": Country("at", "43", "Austria", "🇦🇹"),
    "au": Country("au", "61", "Australia", "🇦🇺"),
    "aw": Country("aw", "297", "Aruba", "🇦🇼"),
    "ax": Country("ax", "358", "Åland Islands", "🇦🇽"),
    "az": Country("az", "994", "Azerbaijan", "🇦🇿"),
    "ba": Country("ba", "387", "Bosnia And Herzegovina", "🇧🇦"),
    "bb": Country("bb", "1", "Barbados", "🇧🇧"),
    "bd": Country("bd", "880", "Bangladesh", "🇧🇩"),
    "be": Country("be", "32", "Belgium", "🇧🇪"),
    "bf": Country("bf", "226", "Burkina Faso", "🇧🇫"),
    "bg": Country("bg", "359", "Bulgaria", "🇧🇬"),
    "bh": Country("bh", "973", "Bahrain", "🇧🇭"),
    "bi": Country("bi", "257", "Burundi", "🇧🇮"),
    "bj": Country("bj", "229", "Benin", "🇧🇯"),
    "bl": Country("bl", "590", "Saint Barthélemy", "🇧🇱"),
    "bm": Country("bm", "1", "Bermuda", "🇧🇲"),
    "bn": Country("bn", "673", "Brunei Darussalam", "🇧🇳"),
    "bo": Country("bo", "591", "Bolivia, Plurinational State Of", "🇧🇴"),
    "br": Country("br", "55", "Brazil", "🇧🇶"),
    "bs": Country("bs", "1", "Bahamas", "🇧🇷"),
    "bt": Country("bt", "975", "Bhutan", "🇧🇸"),
    "bw": Country("bw", "267", "Botswana", "🇧🇹"),
    "by": Country("by", "375", "Belarus", "🇧🇻"),
    "bz": Country("bz", "501", "Belize", "🇧🇼"),
    "ca": Country("ca", "1", "Canada", "🇧🇾"),
    "cc": Country("cc", "61", "Cocos (keeling) Islands", "🇧🇿"),
    "cd": Country("cd", "243", "Congo, The Democratic Republic Of The", "🇨🇦"),
    "cf": Country("cf", "236", "Central African Republic", "🇨🇨"),
    "cg": Country("cg", "242", "Congo", "🇨🇩"),
    "ch": Country("ch", "41", "Switzerland", "🇨🇫"),
    "ci": Country("ci", "225", "Côte D'ivoire", "🇨🇬"),
    "ck": Country("ck", "682", "Cook Islands", "🇨🇭"),
    "cl": Country("cl", "56", "Chile", "🇨🇮"),
    "cm": Country("cm", "237", "Cameroon", "🇨🇰"),
    "cn": Country("cn", "86", "China", "🇨🇱"),
    "co": Country("co", "57", "Colombia", "🇨🇲"),
    "cr": Country("cr", "506", "Costa Rica", "🇨🇳"),
    "cu": Country("cu", "53", "Cuba", "🇨🇴"),
    "cv": Country("cv", "238", "Cape Verde", "🇨🇷"),
    "cw": Country("cw", "599", "Curaçao", "🇨🇺"),
    "cx": Country("cx", "61", "Christmas Island", "🇨🇻"),
    "cy": Country("cy", "357", "Cyprus", "🇨🇼"),
    "cz": Country("cz", "420", "Czech Republic", "🇨🇽"),
    "de": Country("de", "49", "Germany", "🇨🇾"),
    "dj": Country("dj", "253", "Djibouti", "🇨🇿"),
    "dk": Country("dk", "45", "Denmark", "🇩🇪"),
    "dm": Country("dm", "1", "Dominica", "🇩🇯"),
    "do": Country("do", "1", "Dominican Republic", "🇩🇰"),
    "dz": Country("dz", "213", "Algeria", "🇩🇲"),
    "ec": Country("ec", "593", "Ecuador", "🇩🇴"),
    "ee": Country("ee", "372", "Estonia", "🇩🇿"),
    "eg": Country("eg", "20", "Egypt", "🇪🇨"),
    "er": Country("er", "291", "Eritrea", "🇪🇪"),
    "es": Country("es", "34", "Spain", "🇪🇬"),
    "et": Country("et", "251", "Ethiopia", "🇪🇭"),
    "fi": Country("fi", "358", "Finland", "🇪🇷"),
    "fj": Country("fj", "679", "Fiji", "🇪🇸"),
    "fk": Country("fk", "500", "Falkland Islands (malvinas)", "🇪🇹"),
    "fm": Country("fm", "691", "Micronesia, Federated States Of", "🇫🇮"),
    "fo": Country("fo", "298", "Faroe Islands", "🇫🇯"),
    "fr": Country("fr", "33", "France", "🇫🇰"),
    "ga": Country("ga", "241", "Gabon", "🇫🇲"),
    "gb": Country("gb", "44", "United Kingdom", "🇫🇴"),
    "gd": Country("gd", "1", "Grenada", "🇫🇷"),
    "ge": Country("ge", "995", "Georgia", "🇬🇦"),
    "gf": Country("gf", "594", "French Guyana", "🇬🇧"),
    "gh": Country("gh", "233", "Ghana", "🇬🇩"),
    "gi": Country("gi", "350", "Gibraltar", "🇬🇪"),
    "gl": Country("gl", "299", "Greenland", "🇬🇫"),
    "gm": Country("gm", "220", "Gambia", "🇬🇬"),
    "gn": Country("gn", "224", "Guinea", "🇬🇭"),
    "gp": Country("gp", "450", "Guadeloupe", "🇬🇮"),
    "gq": Country("gq", "240", "Equatorial Guinea", "🇬🇱"),
    "gr": Country("gr", "30", "Greece", "🇬🇲"),
    "gt": Country("gt", "502", "Guatemala", "🇬🇳"),
    "gu": Country("gu", "1", "Guam", "🇬🇵"),
    "gw": Country("gw", "245", "Guinea-bissau", "🇬🇶"),
    "gy": Country("gy", "592", "Guyana", "🇬🇷"),
    "hk": Country("hk", "852", "Hong Kong", "🇬🇸"),
    "hn": Country("hn", "504", "Honduras", "🇬🇹"),
    "hr": Country("hr", "385", "Croatia", "🇬🇺"),
    "ht": Country("ht", "509", "Haiti", "🇬🇼"),
    "hu": Country("hu", "36", "Hungary", "🇬🇾"),
    "id": Country("id", "62", "Indonesia", "🇭🇰"),
    "ie": Country("ie", "353", "Ireland", "🇭🇲"),
    "il": Country("il", "972", "Israel", "🇭🇳"),
    "im": Country("im", "44", "Isle Of Man", "🇭🇷"),
    "is": Country("is", "354", "Iceland", "🇭🇹"),
    "in": Country("in", "91", "India", "🇭🇺"),
    "io": Country("io", "246", "British Indian Ocean Territory", "🇮🇩"),
    "iq": Country("iq", "964", "Iraq", "🇮🇪"),
    "ir": Country("ir", "98", "Iran, Islamic Republic Of", "🇮🇱"),
    "it": Country("it", "39", "Italy", "🇮🇲"),
    "je": Country("je", "44", "Jersey ", "🇮🇳"),
    "jm": Country("jm", "1", "Jamaica", "🇮🇴"),
    "jo": Country("jo", "962", "Jordan", "🇮🇶"),
    "jp": Country("jp", "81", "Japan", "🇮🇷"),
    "ke": Country("ke", "254", "Kenya", "🇮🇸"),
    "kg": Country("kg", "996", "Kyrgyzstan", "🇮🇹"),
    "kh": Country("kh", "855", "Cambodia", "🇯🇪"),
    "ki": Country("ki", "686", "Kiribati", "🇯🇲"),
    "km": Country("km", "269", "Comoros", "🇯🇴"),
    "kn": Country("kn", "1", "Saint Kitts and Nevis", "🇯🇵"),
    "kp": Country("kp", "850", "North Korea", "🇰🇪"),
    "kr": Country("kr", "82", "South Korea", "🇰🇬"),
    "kw": Country("kw", "965", "Kuwait", "🇰🇭"),
    "ky": Country("ky", "1", "Cayman Islands", "🇰🇮"),
    "kz": Country("kz", "7", "Kazakhstan", "🇰🇲"),
    "la": Country("la", "856", "Lao People's Democratic Republic", "🇰🇳"),
    "lb": Country("lb", "961", "Lebanon", "🇰🇵"),
    "lc": Country("lc", "1", "Saint Lucia", "🇰🇷"),
    "li": Country("li", "423", "Liechtenstein", "🇰🇼"),
    "lk": Country("lk", "94", "Sri Lanka", "🇰🇾"),
    "lr": Country("lr", "231", "Liberia", "🇰🇿"),
    "ls": Country("ls", "266", "Lesotho", "🇱🇦"),
    "lt": Country("lt", "370", "Lithuania", "🇱🇧"),
    "lu": Country("lu", "352", "Luxembourg", "🇱🇨"),
    "lv": Country("lv", "371", "Latvia", "🇱🇮"),
    "ly": Country("ly", "218", "Libya", "🇱🇰"),
    "ma": Country("ma", "212", "Morocco", "🇱🇷"),
    "mc": Country("mc", "377", "Monaco", "🇱🇸"),
    "md": Country("md", "373", "Moldova, Republic Of", "🇱🇹"),
    "me": Country("me", "382", "Montenegro", "🇱🇺"),
    "mf": Country("mf", "590", "Saint Martin", "🇱🇻"),
    "mg": Country("mg", "261", "Madagascar", "🇱🇾"),
    "mh": Country("mh", "692", "Marshall Islands", "🇲🇦"),
    "mk": Country("mk", "389", "Macedonia (FYROM)", "🇲🇨"),
    "ml": Country("ml", "223", "Mali", "🇲🇩"),
    "mm": Country("mm", "95", "Myanmar", "🇲🇪"),
    "mn": Country("mn", "976", "Mongolia", "🇲🇫"),
    "mo": Country("mo", "853", "Macau", "🇲🇬"),
    "mp": Country("mp", "1", "Northern Mariana Islands", "🇲🇭"),
    "mq": Country("mq", "596", "Martinique", "🇲🇰"),
    "mr": Country("mr", "222", "Mauritania", "🇲🇱"),
    "ms": Country("ms", "1", "Montserrat", "🇲🇲"),
    "mt": Country("mt", "356", "Malta", "🇲🇳"),
    "mu": Country("mu", "230", "Mauritius", "🇲🇴"),
    "mv": Country("mv", "960", "Maldives", "🇲🇵"),
    "mw": Country("mw", "265", "Malawi", "🇲🇶"),
    "mx": Country("mx", "52", "Mexico", "🇲🇷"),
    "my": Country("my", "60", "Malaysia", "🇲🇸"),
    "mz": Country("mz", "258", "Mozambique", "🇲🇹"),
    "na": Country("na", "264", "Namibia", "🇲🇺"),
    "nc": Country("nc", "687", "New Caledonia", "🇲🇻"),
    "ne": Country("ne", "227", "Niger", "🇲🇼"),
    "nf": Country("nf", "672", "Norfolk Islands", "🇲🇽"),
    "ng": Country("ng", "234", "Nigeria", "🇲🇾"),
    "ni": Country("ni", "505", "Nicaragua", "🇲🇿"),
    "nl": Country("nl", "31", "Netherlands", "🇳🇦"),
    "no": Country("no", "47", "Norway", "🇳🇨"),
    "np": Country("np", "977", "Nepal", "🇳🇪"),
    "nr": Country("nr", "674", "Nauru", "🇳🇫"),
    "nu": Country("nu", "683", "Niue", "🇳🇬"),
    "nz": Country("nz", "64", "New Zealand", "🇳🇮"),
    "om": Country("om", "968", "Oman", "🇳🇱"),
    "pa": Country("pa", "507", "Panama", "🇳🇴"),
    "pe": Country("pe", "51", "Peru", "🇳🇵"),
    "pf": Country("pf", "689", "French Polynesia", "🇳🇷"),
    "pg": Country("pg", "675", "Papua New Guinea", "🇳🇺"),
    "ph": Country("ph", "63", "Philippines", "🇳🇿"),
    "pk": Country("pk", "92", "Pakistan", "🇴🇲"),
    "pl": Country("pl", "48", "Poland", "🇵🇦"),
    "pm": Country("pm", "508", "Saint Pierre And Miquelon", "🇵🇪"),
    "pn": Country("pn", "870", "Pitcairn Islands", "🇵🇫"),
    "pr": Country("pr", "1", "Puerto Rico", "🇵🇬"),
    "ps": Country("ps", "970", "Palestine", "🇵🇭"),
    "pt": Country("pt", "351", "Portugal", "🇵🇰"),
    "pw": Country("pw", "680", "Palau", "🇵🇱"),
    "py": Country("py", "595", "Paraguay", "🇵🇲"),
    "qa": Country("qa", "974", "Qatar", "🇵🇳"),
    "re": Country("re", "262", "Réunion", "🇵🇷"),
    "ro": Country("ro", "40", "Romania", "🇵🇸"),
    "rs": Country("rs", "381", "Serbia", "🇵🇹"),
    "ru": Country("ru", "7", "Russian Federation", "🇵🇼"),
    "rw": Country("rw", "250", "Rwanda", "🇵🇾"),
    "sa": Country("sa", "966", "Saudi Arabia", "🇶🇦"),
    "sb": Country("sb", "677", "Solomon Islands", "🇷🇪"),
    "sc": Country("sc", "248", "Seychelles", "🇷🇴"),
    "sd": Country("sd", "249", "Sudan", "🇷🇸"),
    "se": Country("se", "46", "Sweden", "🇷🇺"),
    "sg": Country("sg", "65", "Singapore", "🇷🇼"),
    "sh": Country(
      "sh",
      "290",
      "Saint Helena, Ascension And Tristan Da Cunha",
      "🇸🇦",
    ),
    "si": Country("si", "386", "Slovenia", "🇸🇧"),
    "sk": Country("sk", "421", "Slovakia", "🇸🇨"),
    "sl": Country("sl", "232", "Sierra Leone", "🇸🇩"),
    "sm": Country("sm", "378", "San Marino", "🇸🇪"),
    "sn": Country("sn", "221", "Senegal", "🇸🇬"),
    "so": Country("so", "252", "Somalia", "🇸🇭"),
    "sr": Country("sr", "597", "Suriname", "🇸🇮"),
    "ss": Country("ss", "211", "South Sudan", "🇸🇯"),
    "st": Country("st", "239", "Sao Tome And Principe", "🇸🇰"),
    "sv": Country("sv", "503", "El Salvador", "🇸🇱"),
    "sx": Country("sx", "1", "Sint Maarten", "🇸🇲"),
    "sy": Country("sy", "963", "Syrian Arab Republic", "🇸🇳"),
    "sz": Country("sz", "268", "Swaziland", "🇸🇴"),
    "tc": Country("tc", "1", "Turks and Caicos Islands", "🇸🇷"),
    "td": Country("td", "235", "Chad", "🇸🇸"),
    "tg": Country("tg", "228", "Togo", "🇸🇹"),
    "th": Country("th", "66", "Thailand", "🇸🇻"),
    "tj": Country("tj", "992", "Tajikistan", "🇸🇽"),
    "tk": Country("tk", "690", "Tokelau", "🇸🇾"),
    "tl": Country("tl", "670", "Timor-leste", "🇸🇿"),
    "tm": Country("tm", "993", "Turkmenistan", "🇹🇨"),
    "tn": Country("tn", "216", "Tunisia", "🇹🇩"),
    "to": Country("to", "676", "Tonga", "🇹🇫"),
    "tr": Country("tr", "90", "Turkey", "🇹🇬"),
    "tt": Country("tt", "1", "Trinidad &amp; Tobago", "🇹🇭"),
    "tv": Country("tv", "688", "Tuvalu", "🇹🇯"),
    "tw": Country("tw", "886", "Taiwan", "🇹🇰"),
    "tz": Country("tz", "255", "Tanzania, United Republic Of", "🇹🇱"),
    "ua": Country("ua", "380", "Ukraine", "🇹🇲"),
    "ug": Country("ug", "256", "Uganda", "🇹🇳"),
    "us": Country("us", "1", "United States", "🇹🇴"),
    "uy": Country("uy", "598", "Uruguay", "🇹🇷"),
    "uz": Country("uz", "998", "Uzbekistan", "🇹🇹"),
    "va": Country("va", "379", "Holy See (vatican City State)", "🇹🇻"),
    "vc": Country("vc", "1", "Saint Vincent &amp; The Grenadines", "🇹🇼"),
    "ve": Country("ve", "58", "Venezuela, Bolivarian Republic Of", "🇹🇿"),
    "vg": Country("vg", "1", "British Virgin Islands", "🇺🇦"),
    "vi": Country("vi", "1", "US Virgin Islands", "🇺🇬"),
    "vn": Country("vn", "84", "Vietnam", "🇺🇲"),
    "vu": Country("vu", "678", "Vanuatu", "🇺🇸"),
    "wf": Country("wf", "681", "Wallis And Futuna", "🇺🇾"),
    "ws": Country("ws", "685", "Samoa", "🇺🇿"),
    "xk": Country("xk", "383", "Kosovo", "🇻🇦"),
    "ye": Country("ye", "967", "Yemen", "🇻🇨"),
    "yt": Country("yt", "262", "Mayotte", "🇻🇪"),
    "za": Country("za", "27", "South Africa", "🇻🇬"),
    "zm": Country("zm", "260", "Zambia", "🇻🇮"),
    "zw": Country("zw", "263", "Zimbabwe", "🇻🇳"),
  };

  Country? getCountryFromMap(String nameCode) {
    return countries[nameCode];
  }

  String? getPhoneCode(String nameCode) {
    return countries[nameCode]?.phoneCode;
  }
}
